### ISSUE TITLE
Map is not functioning when cookies have not been accepted

### ISSUE THREAD

**Issue by rudivanhierden** [openstad/openstad-frontend#214]
**Description**
When visiting a frontend with a cookie warning, the map is not functioning until the cookies have been accepted, even though the map provider does not set cookies.

**Suggested fix**
Remove the cookie check for map providers that do not set cookies.

Related ticket: https://trello.com/c/4LKnRuYT/99-google-maps-is-niet-beschikbaar-wanneer-de-cookies-nog-niet-geaccepteerd-zijn

**Comment by ToshKoevoets** [comment]
@rudivanhierden Google Maps sets cookies, seehttps://stackoverflow.com/questions/40995225/avoid-a-google-maps-map-embedded-into-a-web-page-to-store-cookies

From officials in Amsterdam and external users there were a lot of negative reactions on the fact that maps were loaded without asking for cookies first.

Then of course a negative twitter reactions came that they had to accept cookies to load maps.

Twitter is a lovely place :).

But yeah, we now moved to openlayers. Which is also an annoying and big library, and NLMaps also is unstable often returning 404 an 503. So all in all maps is annoying.

We will move te leaflet and drop nlmaps soon.
