### ISSUE TITLE
image-proxy module exposes openstad-image-server to unauthenicated users

### ISSUE THREAD

**Issue by Badmuts** [openstad/openstad-frontend#259]
The [`image-proxy`](https://github.com/Amsterdam/openstad-frontend/blob/master/packages/cms/lib/modules/image-proxy/index.js) module exposes an `/image` and `/images` endpoint which always sets an authorization header. This allows you to upload images to the openstad-image-server without specifying an api token.

For example:

```
curl --request POST \
  --url https://westbegroot.amsterdam.nl/image \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --form image=@some-image.jpg
```

**Comment by nlsvgtr** [comment]
Fixed in https://github.com/Amsterdam/openstad-frontend/pull/261
