### ISSUE TITLE
Fix excessive mongodb connections on every request

### ISSUE THREAD

**Issue by Badmuts** [openstad/openstad-frontend#290]
The serveSite function used to serve an apostrophe site checks if a mongodb exists on every request (https://github.com/Amsterdam/openstad-frontend/blob/master/packages/cms/app.js#L117). To do this is always creates a new mongodb connection and closes it afterwards.

The problem with this approach is that for every request to a frontend page (including css, images and javascript) a new mongodb connection is made to check if the database exists. For example a simple request to [openstad.org](https://openstad.org/) will make 45 request to the frontend service which will result into 45 connections to mongodb. So when openstad.org has 5 active visitors, it needs 225 mongodb connections. 

If possible the connection should be reused instead of created for every call to `dbExists` (https://github.com/Amsterdam/openstad-frontend/blob/master/packages/cms/services/mongo.js#L33). The `serveSite` function (https://github.com/Amsterdam/openstad-frontend/blob/master/packages/cms/app.js#L117) should be restructured to only check if a mongodb exists once when creating a apos server.

This is especially a problem in k8s environments where the ingress does not have proper caching rules in place, so every request to the frontend would result in this middleware being run.

**Comment by ToshKoevoets** [comment]
Solved
